version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  target-branch: next
  ignore:
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
