export { default as ListPokemon } from 'components/ListPokemon'
export { default as Search } from 'components/Search'
export { default as Wrapper } from 'components/Wrapper'
import { default as Header } from 'components/Header'
import { default as Loading  } from 'components/Loading'
